### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by tangm28** [tangm28/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML skeleton
- [x] Add a background for the car to drive on
- [x] Add a car to top left of window using a top-down image of a car
