### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by tangm28** [tangm28/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add data model that includes direction of car (north, south, east, or west)
- [x] Add event listener for arrow key button press
- [x] Add function to turn car in corresponding direction of arrow press.
- [x] Right arrow turns car to the east
- [x] Left arrow turns car to the west
- [x] Up arrow turns car to the north
- [x] Down arrow turns car to the south
