### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by tangm28** [tangm28/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to the data model that holds the car's x and y coordinate
- [x] Car can move forward in the direction it is facing every 16 milliseconds
- [x] Set car's initial coordinate with absolute positioning
- [x] Update the car's coordinate as it moves forward
- [x] Update car's element objects to change the car's top and left box offset to correspond with its location
