### ISSUE TITLE
user-can-stop-their-car

### ISSUE THREAD

**Issue by tangm28** [tangm28/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to check the state of the car
- [x] When boolean is false the car should stop moving forward
- [x] Add an event listener for key press to turn car on and off
