### ISSUE TITLE
user-can-steer-their-car

### ISSUE THREAD

**Issue by tangm28** [tangm28/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] Update code logic to change element style from top left to whichever the corresponding direction is for direction of car
- [ ] Left to Right: current assumptions for style is top left 
- [ ] Right to Left: current assumptions for style is top right
- [ ] Up to Down: current assumptions for style is top bottom
- [ ] Down to Up: current assumptions for style is bottom top
- [ ] Make sure date model's coordinates are updated accordingly to the direction of the car
